version: "3.9"
services:
  db:
    image: postgres:15
    container_name: vinted_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: vinted
      POSTGRES_USER: vinted
      POSTGRES_PASSWORD: vinted_password
    ports:
      - "5437:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
